server:
  port: 0

spring:
  application:
    name: recipient-management-service
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/emergency
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /recipient-management-service/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
