server:
  port: 1000

spring:
  datasource:
    url: jdbc:postgresql://notification-service-postgres:5432/notification
  kafka:
    bootstrap-servers: broker:29092

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
