server:
  port: 0

spring:
  application:
    name: notification-service
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/notification
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    partitions: 10
    topics:
      notifications:
        email: email-notification
        phone: phone-notification
        telegram: telegram-notification
      splitter: recipient-list-splitter

services:
  recipient: recipient-service
  template: template-service
  shortener: url-shortener

springdoc:
  api-docs:
    path: /notification-service/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    metadataMap: # BUG: https://github.com/codecentric/spring-boot-admin/issues/134
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
