version: '3.8'
services:
  postgres:
    image: postgres:alpine3.17
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: emergency
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data
    volumes:
      - db-postgres:/data

  discovery-server:
    image: v1acheslav/discovery-server:1.0.0
    restart: always
    ports:
      - '8761:8761'

  api-gateway:
    image: v1acheslav/api-gateway:1.0.0
    restart: always
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server

  recipient-management-service:
    image: v1acheslav/recipient-management-service:1.0.0
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - api-gateway
      - postgres

volumes:
  db-postgres: { }
