server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: recipient-management-service
          uri: lb://RECIPIENT-MANAGEMENT-SERVICE
          predicates:
            - Path=/recipient-management-service/api-docs/**,/api/v1/recipients/**,/api/v1/files/**,/api/v1/auth/**

# http://localhost:8080/webjars/swagger-ui/index.html
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    url: http://localhost:8080/v3/api-docs
    urls:
      - name: recipient-management-service
        url: /recipient-management-service/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
