server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: recipient-management-service
          uri: lb://RECIPIENT-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/v1/files/**,/api/v1/notifications/**,/api/v1/recipients/**,/api/v1/templates/**
          filters:
            - Authentication
        - id: recipient-management-service-docs
          uri: lb://RECIPIENT-MANAGEMENT-SERVICE
          predicates:
            - Path=/recipient-management-service/api-docs/**

        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: security-service-docs
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/security-service/api-docs/**

# http://localhost:8080/webjars/swagger-ui/index.html
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    url: http://localhost:8080/v3/api-docs
    urls:
      - name: recipient-management-service
        url: /recipient-management-service/api-docs
      - name: security-service
        url: /security-service/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

urls:
  validate: http://localhost:8080/api/v1/auth/validate
