server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: recipient-management-service
          uri: lb://RECIPIENT-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/v1/recipients/**,/api/v1/files/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
