server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: api-service
          uri: lb://API-SERVICE
          predicates:
            - Path=/api/v1/test/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
