server:
  port: 0

spring:
  application:
    name: sender-service
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/emergency
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      notifications:
        email: email-notification
        phone: phone-notification
        telegram: telegram-notification

notification:
  services:
    telegram:
      token: 6080621435:AAG8hChAJ9vKPDEhiZ9_OlhZaqswZi5jk0o

springdoc:
  api-docs:
    path: /sender-service/api-docs

logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR
    com:
      example:
        recipient: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
