server:
  port: 0

spring:
  application:
    name: file-service

services:
  recipient: recipient-service

springdoc:
  api-docs:
    path: /file-service/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    metadataMap: # BUG: https://github.com/codecentric/spring-boot-admin/issues/134
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
