server:
  port: 1002

spring:
  datasource:
    url: jdbc:postgresql://security-service-postgres:5432/security

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
