server:
  port: 0

spring:
  application:
    name: sender
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      notifications:
        email: email-notification
        phone: phone-notification
        telegram: telegram-notification

services:
  notification: notification-service

notification:
  maxRetryAttempts: 3
  services:
    telegram:
      token: 6080621435:AAG8hChAJ9vKPDEhiZ9_OlhZaqswZi5jk0o

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    metadataMap: # BUG: https://github.com/codecentric/spring-boot-admin/issues/134
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
