server:
  port: 1003

spring:
  datasource:
    url: jdbc:postgresql://template-service-postgres:5432/template
  kafka:
    bootstrap-servers: broker:29092

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
