server:
  port: 0

spring:
  application:
    name: rebalancer
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      notifications:
        email: email-notification
        phone: phone-notification
        telegram: telegram-notification

rebalancer:
  seconds-before-resend-pending: 5
  seconds-before-resend-new: 5
  max-amount-to-fetch: 15

services:
  notification: notification-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    metadataMap: # BUG: https://github.com/codecentric/spring-boot-admin/issues/134
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
